version: 0.2

env:
  variables:
    DOCKER_REGISTRY_URL: "210934280793.dkr.ecr.us-east-1.amazonaws.com/my-app"
    
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Entered the install phase...
      - apt-get update -y
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - $(aws ecr get-login --no-include-email --region us-east-1)
    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - docker build -t clair ./coreos-clair
      
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - docker tag clair:latest ${DOCKER_REGISTRY_URL}:clair
      - docker push ${DOCKER_REGISTRY_URL}:clair
      - echo Build completed on `date`